apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}
  labels:
    {{- include "tic-tac-toe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tic-tac-toe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tic-tac-toe.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: {{ include "tic-tac-toe.fullname" . }}
            - secretRef:
                name: {{ include "tic-tac-toe.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "tic-tac-toe.fullname" . }}
            - secretRef:
                name: {{ include "tic-tac-toe.fullname" . }}
