apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}
  labels:
    {{- include "tic-tac-toe.labels" . | nindent 4 }}
type: Opaque
data:
  ANTHROPIC_API_KEY: {{ .Values.secret.anthropicApiKey | b64enc }}
