"""initial

Revision ID: 09794d5025fc
Revises:
Create Date: 2026-03-06 20:44:34.354591

Purpose: Initial database migration creating games and moves tables.
Architecture: Persistence Layer (Migrations).
Notes: Auto-generated by Alembic.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09794d5025fc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("board", sa.String(), nullable=False),
        sa.Column("current_player", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("winner", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "moves",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("move_number", sa.Integer(), nullable=False),
        sa.Column("player", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_moves_game_id"), "moves", ["game_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_moves_game_id"), table_name="moves")
    op.drop_table("moves")
    op.drop_table("games")
    # ### end Alembic commands ###
